### ISSUE TITLE
Integrate a Web-app

### ISSUE THREAD

**Issue by PaulMcInnis** [PaulMcInnis/JobFunnel#95]
**Description**
It would be really nice to have some kind of web-app to use jobfunnel with, perhaps even just to provide a good demo experience.

i.e. https://pages.github.com/

**Describe the solution you'd like**
Ideally the user could run jobfunnel in-browser and review results with a simple web-app.

**Describe alternatives you've considered**
It may be more desirable to make something that runs on a user's local machine, limitations of github pages could prove a blocker.

**Comment by thebigG** [comment]
This is really funny; I was talking to a friend about this a few months ago.  I was thinking more in the lines of a full-blown desktop app for JobFunnel. A GUI where users who aren't very too savvy can just edit the settings file and fire up JobFunnel. This should be relatively straightforward with something like `PyQt` or `WXWdigets`. I would take a stab at it, but my schedule is full at the moment :sweat_smile:.

**Comment by PaulMcInnis** [comment]
PyQT could work if we build standalone apps, but it might not be the best user-experience. I

I'm gonna take a look around this weekend and see what might work nicely... will sync back and update here.

I was also interested in taking a look at GoDot https://godotengine.org/

**Comment by markkvdb** [comment]
I think running jobfunnel on the user's machine should be preferred. Github Pages shines in static pages but is not very suited for dynamic content.

I do agree with @thebigG that many not-so-tech-savy people will have difficulty running the jobfunnel software using a command line. Anecdotal evidence: most of my friends wouldn't even know what a CLI is. Either a web page or a cross-platform GUI could be a solution.

I have zero experience implementing this since most software I write is for tech-savvy people (mostly myself) but I'd love to learn about this, since I believe it's a valuable skill to have.
